### PR TITLE
add image backup functionality to pilot component

### PR DESCRIPTION
**Pull request by ApprenticeofEnder**
- Add image backup functionality (i.e. cloud portrait to local portrait)
- Add local portraits for pilots and mechs in demo data

### CODE REVIEW

**Comment by OmnesPotens** [comment]
I don't really like this implementation because it relies on the user (whoever clones this repo) modifying json that was exported from CompCon. 

Maybe as an alternative, add a key to the  `pilotSpecialInfo` in the `general-config.json`. Something like `alternatePilotImage` and  `alternateMechImage`.

Example: 
```
"pilotSpecialInfo": {
    "APOLLO": {
      "age": "32u",
      "pob": "Evergreen",
      "alternatePilotImage": "/path/to/image",
      "alternateMechImage": "/path/to/image"
    }
}
```

**Comment by OmnesPotens** [comment]
Just adding some other possible options to my above comment: 
- Substitute with an svg/image with error text when a given img src is not found
- Substitute with an svg/image that matches the relevant context. Example: If its a pilot image, substitute in with pilot.svg

**Comment by ApprenticeofEnder** [comment]
> I don't really like this implementation because it relies on the user (whoever clones this repo) modifying json that was exported from CompCon.
> 
> Maybe as an alternative, add a key to the `pilotSpecialInfo` in the `general-config.json`. Something like `alternatePilotImage` and `alternateMechImage`.
> 
> Example:
> 
> ```
> "pilotSpecialInfo": {
>     "APOLLO": {
>       "age": "32u",
>       "pob": "Evergreen",
>       "alternatePilotImage": "/path/to/image",
>       "alternateMechImage": "/path/to/image"
>     }
> }
> ```

That could definitely work, and I can see why modifying JSON directly would be annoying. I'll see if I can make those changes soon.

**Comment by Kuenaimaku** [comment]
realistically, pilot and mech information (as @OmnesPotens pointed out before, should probably be moved to a roster or characters directory) should be pulled from COMP/CON whenever possible, and require no editing of said JSON file. I think falling back to an image not found as specified above is the correct thing to do in this case.

As for showing that additional background information, its something that doesn't have to be on the pilot roster, so it could be replaced with other information if needed (but it feels like something that would be in a dossier, so...)

**Pull request closed without merging**
